UnitOfWorkPaging/UnitOfWorkPaging/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UnitOfWorkPaging.Models
{
    public class Category
    {
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
    }
}

UnitOfWorkPaging/UnitOfWorkPaging/Models/ErrorViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UnitOfWorkPaging.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

UnitOfWorkPaging/UnitOfWorkPaging/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UnitOfWorkPaging.Models
{
    public class Product
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public int CategoryID { get; set; }
    }
}

UnitOfWorkPaging/UnitOfWorkPaging/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using UnitOfWorkPaging.Models;

namespace UnitOfWorkPaging.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

UnitOfWorkPaging/UnitOfWorkPaging/Controllers/ProductController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using UnitOfWorkPaging.Interfaces;
using UnitOfWorkPaging.Models;

namespace UnitOfWorkPaging.Controllers
{
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public ProductController(IUnitOfWork unitOfWork)
        {
            _unitOfWork=unitOfWork;
        }

        public IActionResult GetByCategoryId(int id,int page=1,int pageSize=3)
        {
            var productList = _unitOfWork.ProductRepository.GetByCategoryId(id);
            X.PagedList.PagedList<Product> model = new X.PagedList.PagedList<Product>(productList.Where(a => a.CategoryID == id), page, pageSize);
            return View(model);

        }


        public IActionResult Index()
        {
            return View();
        }
    }
}

UnitOfWorkPaging/UnitOfWorkPaging/ViewComponents/MenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;

using UnitOfWorkPaging.Interfaces;

namespace UnitOfWorkPaging.ViewComponents
{
    public class MenuViewComponent:ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;
        public MenuViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;  
        }
        public IViewComponentResult Invoke()
        {
            var categories = _unitOfWork.CategoryRepository.List();
            return View(categories);
        }
    }
}

UnitOfWorkPaging/UnitOfWorkPaging/Views/Home/Index.cshtml


<h1>Index</h1>


UnitOfWorkPaging/UnitOfWorkPaging/Views/Product/GetByCategoryId.cshtml


@model X.PagedList.PagedList<Product>
@using X.PagedList.Mvc.Core

@{
    ViewData["Title"] = "GetByCategoryId";
}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css?family=Exo+2" rel="stylesheet">
<script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/js/bootstrap.min.js"></script>
<div style="padding-top:17px">
    <h1 class="page-header">

        Ürün Listesi

       
    </h1>

</div>

<input type="hidden" id="CategoryId" value="categoryId" />
<div style="padding-top:50px" id="Holder-Products">

</div>


<div class="col-sm-9 col-md-10 main">
    <table class="table">
        <tr>
            <th><strong>Ürün Adı</strong></th>

            <th><strong>Ürün Açıklaması</strong></th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            @item.ProductName
            <br />
        }

        <tr>
            <td colspan="5" class="deneme">
                @Html.PagedListPager(Model, page => Url.Action("GetByCategoryId", new { page }))
            </td>
        </tr>

    </table>


</div>


UnitOfWorkPaging/UnitOfWorkPaging/Views/Shared/Components/Menu/Default.cshtml
@model IEnumerable<Category>

<div id="menu">
    <ul>
        @foreach (var category in Model)
        {
            <li> <a href="@Url.Action("GetByCategoryId", "Product", new { id = category.CategoryID})" class="list-group-item">@category.CategoryName</a></li>
        }
    </ul>
</div>


UnitOfWorkPaging/UnitOfWorkPaging/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style>
        #header {
            width: 900px;
            height: 100px;
            border-radius: 20px;
            background: red;
            padding: 20px;
            margin-bottom: 10px;
        }

        #menu {
            width: 200px;
            height: 300px;
            border-radius: 20px;
            background: rebeccapurple;
            padding: 20px;
            float: left;
        }


        ul {
            margin: 0;
            padding: 0;
        }

        #menu li {
            list-style: none;
            padding: 10px;
        }

        #menu a {
            color: red;
            text-decoration: none;
        }

        .pagination-container {
            list-style: none;
        }

            .pagination-container li {
                display: inline;
            }

        #content {
            float: left;
            width: 650px;
            height: 300px;
            border-radius: 20px;
            background: blue;
            padding: 20px;
            margin-left: 10px;
        }
    </style>
</head>
<body>


    <div class="row">
        <div class="col-md-4">@await Component.InvokeAsync("Menu")</div>
        <div class="col-md-2"></div>
        <div class="col-md-6">

            @RenderBody()

        </div>
    </div>


</body>
</html>